language: node_js
node_js:
  - node

os: linux
dist: bionic

before_install:
  - npm install typescript -g
  
script:
  - tsc
  
cache: npm

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(release|TravisCI)
