name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install and Build
        run: |
          npm ci
          npx tsc
          mkdir dist
          cp src/index.html dist/index.html
          cp src/style.css dist/style.css
          cp src/websocket.js dist/websocket.js

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
